// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC0CChdu1GUW0NIcl6QyZxDdP3j4oEpvVc',
    appId: '1:878552149487:web:94a5ce881fdbece78a5a1a',
    messagingSenderId: '878552149487',
    projectId: 'tarefas-254ba',
    authDomain: 'tarefas-254ba.firebaseapp.com',
    storageBucket: 'tarefas-254ba.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBwxi84j4EvFI2Iexj_SIy_dszHNbPeQbo',
    appId: '1:878552149487:android:d6293c2e799e6f438a5a1a',
    messagingSenderId: '878552149487',
    projectId: 'tarefas-254ba',
    storageBucket: 'tarefas-254ba.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyACg31gz4ZBItVbdA2XGhVFbUNjFe6INxk',
    appId: '1:878552149487:ios:275f77cb1ecc412a8a5a1a',
    messagingSenderId: '878552149487',
    projectId: 'tarefas-254ba',
    storageBucket: 'tarefas-254ba.firebasestorage.app',
    iosBundleId: 'com.example.project',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyACg31gz4ZBItVbdA2XGhVFbUNjFe6INxk',
    appId: '1:878552149487:ios:275f77cb1ecc412a8a5a1a',
    messagingSenderId: '878552149487',
    projectId: 'tarefas-254ba',
    storageBucket: 'tarefas-254ba.firebasestorage.app',
    iosBundleId: 'com.example.project',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC0CChdu1GUW0NIcl6QyZxDdP3j4oEpvVc',
    appId: '1:878552149487:web:443d3b784db791298a5a1a',
    messagingSenderId: '878552149487',
    projectId: 'tarefas-254ba',
    authDomain: 'tarefas-254ba.firebaseapp.com',
    storageBucket: 'tarefas-254ba.firebasestorage.app',
  );
}
